name: m4d_translate_sample
description: Material4Dart (m4d) 'm4d_translate' Sample
version: 0.1.0
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/m4d_translate

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:

  logging: '>=0.11.3 <1.0.0'
  console_log_handler: ^1.0.0
    # git: git@github.com:MikeMitterer/dart-console_log_handler.git
  # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  m4d_translate:
    path: ../..

  m4d_components: '>=0.1.0 <1.0.0'
   # path: /Volumes/Daten/DevLocal/DevDart/m4d/m4d_components

dev_dependencies:
  build_runner: any
  build_web_compilers: any

  sass_builder: any